Dockerfile.cpu: add `arrayfire-unified3` package
Fixes the following runtime dependency issue (presumably introduced by af v3.8.3):

```
$ docker run --rm $CPU_TEST_IMAGE ./bash/runalltests.sh
running test '../build/magnumaf/test/test*':
running test '../python/test/test_atomistic_anisotropy.py'
Traceback (most recent call last):
  File "../python/test/test_atomistic_anisotropy.py", line 2, in <module>
    import arrayfire as af
  File "/usr/local/lib/python3.8/dist-packages/arrayfire/__init__.py", line 56, in <module>
    from .library    import *
  File "/usr/local/lib/python3.8/dist-packages/arrayfire/library.py", line 751, in <module>
    backend = _clibrary()
  File "/usr/local/lib/python3.8/dist-packages/arrayfire/library.py", line 726, in __init__
    raise RuntimeError("Could not load any ArrayFire libraries.\n" + more_info_str)
RuntimeError: Could not load any ArrayFire libraries.
Please look at https://github.com/arrayfire/arrayfire-python/wiki for more information.
```